<?php

/**
 * Implements hook_services_resources().
 */
function ckan_services_services_resources() {
 $session_resource = array(
    'session' => array(
      'operations' => array(
        'retrieve' => array(
          'callback' => 'ckan_services_session_get',
          'args' => array(
            array(
              'name' => 'sid',
              'optional' => FALSE,
              'source' => array('data' => 'sid'),
              'type' => 'string',
              'description' => 'Session ID',
            ),
          ),
          'access callback' => 'ckan_services_access',
        ),
      ),
    ),
  );
  return $session_resource;
}

/**
 * Gets an User ID from a Session ID
 *
 * @param $sid Session ID
 */
function ckan_services_session_get($sid = null) {
  global $user;
  if (!$sid) {
    $sid = $user->sid;
  }

  return db_select('sessions', 's')
    ->fields('s', array('uid'))
    ->condition('sid', $sid)
    ->execute()
    ->fetchField();
}

/**
 * Allows anonymous users
 */
function ckan_services_access() {
	return TRUE;
}
