<?php

/**
 * Implements hook_init.  Used to redirect to the corresponding page in the
 * LandBook when searching for the LandBook nodes.
 *
 * We used hook_init instead hook_page_view because the latest is also called
 * when the nodes are indexed for search and breaks the index.
 */
function landbook_nodes_access_init() {
    $node = menu_get_object();
    if (isset($node->type)):
        $landbook_id = $node->field_id['und'][0]['value'];
        switch ($node->type):
            case "landbook_country":
                drupal_goto("book/countries/$landbook_id");
                break;
            case "landbook_indicator":
                // The second parameter is required to send the querystring properly
                drupal_goto('book/indicators/detail', array(
                    'query' => array(
                        'indicator' => $landbook_id,
                    )
                ));
                break;
        endswitch;
    endif;
}
